# Generated by Django 3.0.4 on 2020-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manors',
        ),
    ]
