# Generated by Django 3.0.4 on 2020-04-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_datisdlogs_datiswlogs_dscndlogs_employee_mcdo_vhfdlogs_vhfmlogs_vhfylogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdvordlogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'cdvordlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cdvorwlogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'cdvorwlogs',
                'managed': False,
            },
        ),
    ]
