# Generated by Django 3.0.4 on 2020-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_cdvormlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scctvdlogs',
            fields=[
                ('value', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'scctvdlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scctvmlogs',
            fields=[
                ('value', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'scctvmlogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scctvwlogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'scctvwlogs',
                'managed': False,
            },
        ),
    ]
