# Generated by Django 3.0.4 on 2020-05-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_dgmreports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mcdo',
        ),
    ]
